### ISSUE TITLE
JMSParser change property name for snake_case by default

### ISSUE THREAD

**Issue by rafaa1994** [liip/metadata-parser#16]
Where we are using JMS annotations JMSParser by default it changed property name to snake_case notation.

`liip/metadata-parser/src/ModelParser/JMSParser.php:294` 

That's huge issue because JMS serializer works that if we don't annotate `@SerializedName` by default we are getting property name, because of that serialized property name in jsonData is not matching to object. 
Deserialization Class:

```php
/**
  * @Serializer\Type("boolean")
  * @Serializer\Accessor(getter="isTotalHotelBoxesCountApproximate", setter="setIsTotalHotelBoxesCountApproximate")
  *
  * @var bool $isTotalHotelBoxesCountApproximate
  */
private $isTotalHotelBoxesCountApproximate;
```
Generated liip file:

```php
if (isset($modelTotalHotelBoxesCount)) {
    $model->setTotalHotelBoxesCount($modelTotalHotelBoxesCount);

}
unset($modelTotalHotelBoxesCount);
if (isset($jsonData['is_total_hotel_boxes_count_approximate'])) {
    $modelIsTotalHotelBoxesCountApproximate = $jsonData['is_total_hotel_boxes_count_approximate'];

```
But `$jsonData` is keeping `isTotalHotelBoxesCountApproximate` instead of `is_total_hotel_boxes_count_approximate`

There is also no possibility to force serializedName even property name is the same when we are using also PhpDocParser. 
Error which appear `You can not rename is_total_hotel_boxes_count_approximate into isTotalHotelBoxesCountApproximate as it is the same property. Did you miss to handle camelCase properties with PropertyCollection::serializedName?`

Here I used that code
Class:

```php
/**
  * @Serializer\SerializedName(value="isTotalHotelBoxesCountApproximate")
  * @Serializer\Type("boolean")
  * @Serializer\Accessor(getter="isTotalHotelBoxesCountApproximate", setter="setIsTotalHotelBoxesCountApproximate")
  *
  * @var bool $isTotalHotelBoxesCountApproximate
  */
private $isTotalHotelBoxesCountApproximate;
```

Parser:

```php
$parsers = [
    new PhpDocParser(),
    new JMSParser(new AnnotationReader()),
];
$builder = new Builder(new Parser($parsers), new RecursionChecker(new NullLogger(), []));

```

**Comment by dbu** [comment]
we built this initially to fit our need - looking at https://github.com/liip/metadata-parser/blob/master/src/ModelParser/JMSParser.php#L295 i think we try to handle the serialized name annotation, so at least the per-property option is supposed to work already.

can you do a pull request with a functional test that reproduces the problem? that would be a good first step to identify what exactly goes wrong.

for a global configuration, we could add an optional $options parameter to the JMSParser constructor to allow changing the property naming strategy and respect that on line 294. want to do a pull request for that as well?

**Comment by rafaa1994** [comment]
But it is standard behaviour and even tests assume that JMSParser should return `serializedName` in snake_case notation.
https://github.com/liip/metadata-parser/blob/87c9be0fc337fdf239ac5c97d87b8caff7bba74f/tests/ModelParser/JMSParserTest.php#L646

It makes from `$proPerty3` -> `pro_perty3`. It happens because
PropertyMetadata is created via static method `fromRawProperty` in PropertyReducer 
https://github.com/liip/metadata-parser/blob/87c9be0fc337fdf239ac5c97d87b8caff7bba74f/src/PropertyReducer.php#L31

It has serialized name from set value from static method 
https://github.com/liip/metadata-parser/blob/87c9be0fc337fdf239ac5c97d87b8caff7bba74f/src/ModelParser/RawMetadata/PropertyCollection.php#L31.

I think now, that is not the issue of metadata-parser but serializer which for DeserializeGenerator and SerializerGenerator take this `getSerializedName()` instead of proper which is set via annotation or reflection property name via `getName()`.

https://github.com/liip/serializer/blob/d4b4bd4138e00d9dda90cd7cad4dbbbdf55dde51/src/DeserializerGenerator.php#L117
https://github.com/liip/serializer/blob/d4b4bd4138e00d9dda90cd7cad4dbbbdf55dde51/src/SerializerGenerator.php#L145

**Comment by dbu** [comment]
can you do a pull request with a test that makes the problem happen? then i can have a look where we would need to change things to handle this case correctly.

**Comment by dbu** [comment]
with https://github.com/liip/metadata-parser/pull/28 it is now possible to switch to `identity` naming strategy, in addition to snake_case.

it would also be possible to add full support of the jms naming strategies if somebody wants to do a pull request for that.
