### ISSUE TITLE
release 1.0?

### ISSUE THREAD

**Issue by dbu** [liip/metadata-parser#34]
time to tag a stable version 1?

we use this in a large project since a while and have not run into problems.

@Spea you contributed a couple of things, do you have any input on this? or any BC breaks in mind that we should do while we still can?

**Comment by Spea** [comment]
Can't think of anything as of right now. We are still in the process of migrating to liip-serializer, but as of right now nothing else came up that would require a adjustment of this library.

**Comment by dbu** [comment]
tagged 1.0.0 now :tada:
